### ISSUE TITLE
unable to start server using provided info.

### ISSUE THREAD

**Issue by Pesoen** [azixus/ARK_Ascended_Docker#23]
i'm still relatively new to docker, so when it throws such a generic error, i have no clue where to even start finding the issue.. any ideas out there?
```
mkdir: cannot create directory '': No such file or directory
+ mkdir -p ''
```
everytime it tries to start, it will add these two lines and nothing else will happen, and it will say "Stopped for X minutes with exit code 1"

tried another one before this, but that did not even give me anything in the logs before stopping.

**Comment by azixus** [comment]
At first glance, this looks like the `.env` file is ignored and no environment variables are loaded during the startup. Could you make sure that you're using docker compose v2, (i.e., are you running the container with `docker-compose` or `docker compose`). If not uninstall the current version and follow the guide here: https://docs.docker.com/engine/install/ubuntu/

Otherwise, if you have modified the `.env` file, make sure that the default variables are still there. In particular `STEAM_COMPAT_CLIENT_INSTALL_PATH`, `LOG_FILE` as these could directly be linked to that error.

**Comment by Pesoen** [comment]
i did modify the .env file, but only changed the session name, password and admin password. the rest is left default as pr the install instructions. though i did set it all up using portainer, that should not make any difference.

other than that i only modified the volumes, as i wanted the files to be in a specific folder on our server, but all folders where made on it's own when i started the stack. only thing with volumes i did not change was the steamcmd one, left that as is.

hold up, might have found the problem, will write if my assumption is correct and close the issue, i might have been stupid. if not i will write here again if my assumption is not correct.

**Comment by Pesoen** [comment]
yup, i was an idiot, forgot folder permissions on the folder i wanted to use for the server files.. so it was trying to write to a folder it was not allowed to, not sure why i forgot that part..
