### ISSUE TITLE
2 docker server

### ISSUE THREAD

**Issue by NRmash** [azixus/ARK_Ascended_Docker#30]
Hey,

is there a way to run your docker version twice simultaneously on a linux server?

greez

**Comment by azixus** [comment]
Currently, the the safest way is to clone the repo in two different directories and use different ports. One issue with this method is that you actually need to store the server files twice.

I'll try to improve this in the future.

**Comment by NRmash** [comment]
> Currently, the the safest way is to clone the repo in two different directories and use different ports. One issue with this method is that you actually need to store the server files twice.
> 
> I'll try to improve this in the future.

thx :)

**Comment by NRmash** [comment]
Hey,

since traveling is now possible i would be very happy if there would be a possibility to use 2 servers at the same time :)

**Comment by jmaggart1979** [comment]
I love this project and I appreciate all the work that has gone into it! I'm currently running 3 different containers for different ark setups that I mess around with.

I would also appreciate having the ability to cluster servers since Scorched is coming out and would love to transfer. Any updates on this would be awesome.

**Comment by NIREKI** [comment]
> I love this project and I appreciate all the work that has gone into it! I'm currently running 3 different containers for different ark setups that I mess around with.
> 
> I would also appreciate having the ability to cluster servers since Scorched is coming out and would love to transfer. Any updates on this would be awesome.

Thanks for your kind words @jmaggart1979, appreciate it! It also seems like clustering is officially supported since some patches now ([according to their patchnotes](https://survivetheark.com/index.php?/forums/topic/708761-asa-pc-patch-notes-client-v3623-server-v3627-updated-03292024/#:~:text=If%20you%20are%20running%20your%20own%20cluster%20you%20can%20enable%20this%20with%3A%20-clusterID%3D%5Bclustername%5D)). 

> If you are running your own cluster you can enable this with: -clusterID=[clustername]

So, just go into the `.env` files of both your servers and add the -clusterID=blablabla into the`ARK_EXTRA_DASH_OPTS` so it looks (for example) like this:
```
ARK_EXTRA_DASH_OPTS=-ForceAllowCaveFlyers -ForceRespawnDinos -AllowRaidDinoFeeding=true -ActiveEvent=Summer -clusterID=thisisarandomid
```
We could edit the .env file to make this a bit easier, but this should already be as straight forward as it gets. Wildcard really should step up their documentation game.

**Comment by NIREKI** [comment]
I think closing this issue as "wontfix" would be the best thing to do. With Scorched Earth now released, it wouldn't even make sense to reduce server file size because of the different maps. 

### Quick Guide for running a cluster:
- Clone this repository into **two different directories** like `/opt/arkserver_theisland` and `/opt/arkserver_scorchedearth`
- Edit the `.env` file accordingly, **make sure that both servers use different ports** (Edit `SERVER_PORT=7790` to like 7791, 7792 eg)
- Add the `COMPOSE_PROJECT_NAME=somename` line to the .env file. Otherwise docker compose gets confused when using the same services two times. 
- If you want to **cluster** them: add `-clusterID=[yourclusterid]` to the `ARK_EXTRA_DASH_OPTS` in the `.env` file, make sure to use the same clusterId for both servers and change it to something random, don't use special characters.
- Be aware that you have to update both servers seperately, or you could write a small script updating them, or use a discord bot like [this one](https://github.com/NIREKI/DockerDiscordBot).

**Comment by jmaggart1979** [comment]
Thanks for the replies and the quick guide. I was aware of the clusterid settings (but wasn't sure where to put it), and the server port difference. Unfortunately, with just those changes I am not able to transfer.  The server is available, the gus.ini settings to enable crossark transfers are correct but when I get to the second server spawn screen it takes me to the character creation.

Most of the documentation I was seeing online is that there needs to be either a environmental variable to call out the cluster folder or a way to indicate the cluster directory override. Am I not understanding that correctly?

I don't know enough about docker compose files so when I try to do it I just keep screwing something up.

**Comment by NIREKI** [comment]
@jmaggart1979 yeah, you could be right, that you probably need the `-ClusterDirOverride` variable. And, if I understand this correctly, both servers need to use the same Directory. If you want to, you can hit me up on Discord and we could test this together. My username is nirekiki.

I think this is how it should work:

1. create a folder for the shared data. Let`s say `/opt/clusters` and grant the right permissions to it with `chown -R 1000:1000 /opt/clusters`
2. Edit the docker-compose.yml of both servers, add the same volume to both servers:
```
volumes:
      - ./ark_data:/opt/arkserver
      - ./ark_backup:/var/backups/asa-server
      - /opt/clusters:/opt/shared-cluster#<-- This means that data in the container saved in the local /opt/clusters folder get's saved on your host in the previously created /opt/clusters folder
      - steam_data:/opt/steamcmd
```
3. Edit the .env file and add the -ClusterDirOverride variable, it should look like the following:
```
ARK_EXTRA_DASH_OPTS=-ForceAllowCaveFlyers -ForceRespawnDinos -AllowRaidDinoFeeding=true -ActiveEvent=Summer -clusterID=yourid -ClusterDirOverride="/opt/shared-cluster"
```
4. Now both servers should be able to access the same data and copy data between each other.

**Comment by jmaggart1979** [comment]
@NIREKI I would love to help test it. I can most likely be on later this evening (I'm in Colorado, US) after I finish with classes and family stuff.

One other thought to consider is implementing something like [this](https://github.com/Acekorneya/Ark-Survival-Ascended-Server) where you could have multiple instances and a cluster setup. Not implying to steal this person's stuff but just thought it might be an inspiration for updates.

**Comment by NIREKI** [comment]
> One other thought to consider is implementing something like [this](https://github.com/Acekorneya/Ark-Survival-Ascended-Server) where you could have multiple instances and a cluster setup. Not implying to steal this person's stuff but just thought it might be an inspiration for updates.

I mean yeah, why not, the manager of this project could do much more things and I can tell you that we initially had some plans to add some features to it. But idk, the container worked, we never really needed more than one instance running at the same time so it was more or less abondoned because there really was no value to invest even more time into this project.

At the end it should work flawlessly with the extra folder and the other requirements I've listed earlier. The server then would actually meet all the requirements I could find in the ARK Forum. But yeah, you are absolutely right, that this docker image could be improved in many ways to make it much easier.

**Comment by jmaggart1979** [comment]
>But idk, the container worked, we never really needed more than one instance running at the same time so it was more or less abondoned because there really was no value to invest even more time into this project.

That makes sense. I wan't meaning to insult or anything.

> At the end it should work flawlessly with the extra folder and the other requirements I've listed earlier. The server then would actually meet all the requirements I could find in the ARK Forum. 

That's cool. I can help test that piece so if others who are using this image want to cluster servers they have it will work.

**Comment by NIREKI** [comment]
@jmaggart1979 good news: it works! @azixus was kind enough to test my small guide, and player transfer works this way. Just follow [this section of the updated readme.md file](https://github.com/azixus/ARK_Ascended_Docker/tree/cluster?tab=readme-ov-file#running-multiple-instances-cluster), and everything should work. If you have further questions/recommendations or problems, feel free to open this issue again or write me a pn over at discord :)
